LSTM

aşamalarımız:\
1- import libraries\
2- create dataset\
3- tokenizer and dizilerin hazırlanması\
4- metinleri sıralayalim ve padding işlemi uygulayalım\
5- crete LSTM model\
6- train LSTM model\
7- evaluation ve metin tamamlama calismasi

amacımız: kelime girdiğinde devamını modleimizin getriemsini istiyoruz

In [12]:
import numpy as np
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Embedding
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [13]:
texts = [
        "Merhaba, nasılsınız? Ben oldukça iyiyim.", 
        "Spor yaparken enerjim artıyor ve kendimi iyi hissediyorum.",
        "Bugün hava çok güzel, dışarıda yürüyüş yapmalıyım.",
        "Akşam yemeği için ne pişireceğim konusunda kararsızım.",
        "Yarın arkadaşlarımla buluşmaya gideceğim.",
        "Kütüphaneye gidip yeni kitaplar almayı düşünüyorum.",
        "İşim çok yoğun ama bu hafta sonu tatil yapmayı planlıyorum.",
        "Kahvemi almayı unuttum, hemen bir fincan içmeliyim.",
        "Bugün film izlemeyi çok istiyorum.",
        "Sabah erken kalkıp güne dinç başlamak harika oldu.",
        "Tatile çıkmaya karar verdik, çok heyecanlıyım.",
        "Yaz tatilinde denize girmeyi dört gözle bekliyorum.",
        "Yeni bir dil öğrenmeye başlamak istiyorum.",
        "Bugün biraz meditasyon yapıp rahatlamak iyi olabilir.",
        "Kışın soğuk havası beni biraz zorlıyor.",
        "Dün akşam bir arkadaşım ile uzun uzun sohbet ettik.",
        "Yeni bir telefon almak istiyorum, hangi model daha iyi?",
        "Köpeğimle parka çıkıp biraz yürüyüş yapacağım.",
        "Bugün biraz alışveriş yapıp eksik olan şeyleri alacağım.",
        "Sinemaya gitmek çok eğlenceli olacak.",
        "Ailemle hafta sonu yemek yemeyi planlıyoruz.",
        "Yolda yürürken çok güzel çiçekler gördüm.",
        "Evde biraz temizlik yapmam gerek.",
        "Dün gece çok geç uyudum, biraz uykusuzum.",
        "Yaz tatilinde tatile gitmek için birkaç planım var.",
        "Kitap okumak benim için çok rahatlatıcı bir aktivite.",
        "Bazen uzun yürüyüşler yapmak ruhumu dinlendiriyor.",
        "Bugün çok çalıştım, biraz dinlenmeliyim.",
        "Öğle yemeği için ne yesem acaba?",
        "Arkadaşımın doğum günü partisinde çok eğlendim.",
        "Yeni bir müzik aleti çalmayı öğrenmeye karar verdim.",
        "Bugün pazara gitmek istiyorum, alışveriş yapmam gerekiyor.",
        "Akşam yemeği için pizza yapmayı düşünüyorum.",
        "Tatil için hazırlıklarımı yapmaya başladım.",
        "Günlük alışkanlıklarımı düzene sokmaya karar verdim.",
        "Bana biraz motivasyon lazım, bugün iyi bir gün olacak.",
        "Gün sonunda biraz meditasyon yaparak rahatlamayı planlıyorum.",
        "Bugün arkadaşım bana sürpriz yaptı, çok mutlu oldum.",
        "Sabah kahvemi içmeden asla işe başlamam.",
        "Bazen uzun yürüyüşler yapmak bana çok iyi geliyor.",
        "Kitap okumak bana çok şey katıyor, her gün bir sayfa okumaya karar verdim.",
        "Dışarıda rüzgar var ama yine de yürüyüş yapmayı planlıyorum.",
        "Yeni bir telefon almak istiyorum, hangisini önerirsiniz?",
        "Akşam film izlemek için güzel bir seçenek olabilir.",
        "Daha fazla su içmem gerekiyor, bugün yeterince içmedim.",
        "Bugün biraz yoga yapmayı düşünüyorum, rahatlamaya ihtiyacım var.",
        "Bazen evde sakin bir ortamda sadece müzik dinlemek güzel oluyor.",
        "Kendime yeni bir hedef belirledim, ona odaklanacağım.",
        "Ailemle dışarıda güzel bir akşam yemeği yedik.",
        "Bugün güne erken başladım ve verimli geçti.",
        "Spor salonuna yazıldım, bu hafta başlıyorum.",
        "Dışarıda yağmur yağıyor ama yine de dışarı çıkmak istiyorum.",
        "Yeni bir hobi edinmeyi düşünüyorum.",
        "Bugün bir arkadaşım bana çok güzel bir hediye verdi.",
        "Her gün biraz yürüyüş yapmak istiyorum, sağlığım için önemli.",
        "Dün akşam çok lezzetli bir yemek yaptım, tarifimi arkadaşlarıma vereceğim.",
        "Bazen evde vakit geçirmek bana iyi geliyor.",
        "Bugün arkadaşımın doğum günü, ona bir sürpriz hazırladım.",
        "Akşam yemeği için makarna yapmayı planlıyorum.",
        "Bugün işe gitmek zor ama hafta sonu tatil var.",
        "Daha fazla egzersiz yapmalıyım, sağlığım için çok önemli.",
        "Bu sabah çok enerjik hissettim, çok verimli bir gün oldu.",
        "Arkadaşlarım bana bugün gerçekten güzel bir gün yaşattılar.",
        "Bugün biraz alışveriş yapmalıyım, eksik şeyler var.",
        "Kendime yeni bir kitap aldım, bu akşam okumayı düşünüyorum.",
        "Evdeki her şey çok dağınık, biraz toparlamalıyım.",
        "Bugün çok güzel bir sabah yürüyüşü yaptım.",
        "Yarın sabah erken kalkıp kahvaltıya gideceğim.",
        "Günümüzde teknoloji çok hızlı gelişiyor.",
        "Birçok yeni şey öğrenmek istiyorum.",
        "Çalışma masamı düzenlemem gerek, çok dağınık.",
        "Evde dinlenmek çok iyi geliyor, özellikle hafta sonları.",
        "Bugün hava biraz kapalı ama yine de dışarı çıkmalıyım.",
        "Çok fazla çay içiyorum, biraz azaltmalıyım.",
        "Bu akşam sinemaya gitmek istiyorum.",
        "Arkadaşlarımla birlikte dışarıda bir etkinlik yapmayı düşünüyorum.",
        "Bugün biraz sanat galerisi gezmeye karar verdim.",
        "Birkaç hafta önce başladığım projeyi bitirmeliyim.",
        "Çalışma odamı yeniden düzenleyeceğim.",
        "Yaz tatilinde nereye gitmek istediğimi düşünüyorum.",
        "Bazen dışarıda arkadaşlarla yürümek çok rahatlatıcı oluyor.",
        "Evde yoga yapmayı çok seviyorum.",
        "Bu hafta sonu bir tatile çıkmayı düşünüyorum.",
        "Bugün spor salonuna üye oldum, artık daha fazla çalışacağım.",
        "Dışarıda yürürken çok güzel manzaralar gördüm.",
        "Günümü planlamak için biraz zaman ayırmalıyım.",
        "Biraz müzik dinlemek bana gerçekten iyi geliyor.",
        "Bugün fazla yürüdüm, biraz dinlenmem gerek.",
        "Evde kaldığımda kitap okumak bana çok iyi geliyor.",
        "Yemek yaparken yeni tarifler denemek çok eğlenceli.",
        "Arkadaşım bu sabah benden yardım istedi.",
        "Bu hafta sonu piknik yapmaya karar verdim.",
        "Kendimi geliştirmek için online kurslara katılmayı planlıyorum.",
        "Bugün çok güzel bir gün, kesinlikle dışarı çıkmalıyım.",
        "Bazen hayatın tadını çıkarmak için yavaşlamak gerek.",
        "Bugün çok işim vardı ama yine de çok mutlu oldum.",
        "Herkesin sağlıklı kalması önemli, spor yapmayı ihmal etmemeliyiz.",
        "Bu akşam yeni bir dizi izlemeye başlayacağım.",
        "Kahvaltı yapmayı asla atlamam, güne enerjik başlamak için çok önemli.",
        "Gün boyunca çok çalıştım ama sonunda güzel bir akşam yemeği hazırladım.",
        "Dışarıda yağmur yağıyor ama hala yürüyüş yapmak istiyorum."
    ]

In [14]:
print(len(texts))

101


3- tokenizer ve dizileirn hazirlanmasi

In [15]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)
total_words = len(tokenizer.word_index) + 1

4- metin siralayalim ve padding islemi uygulayalim

In [27]:
input_sequences = []
for text in texts:
    token_list = tokenizer.texts_to_sequences([text])[0]
    for i in range(1, len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

input_sequences[:10] # ilk 10 tane goster sayialrin her biri bir kelimeyi ifade ediyor

[[118, 119],
 [118, 119, 120],
 [118, 119, 120, 121],
 [118, 119, 120, 121, 122],
 [32, 59],
 [32, 59, 123],
 [32, 59, 123, 124],
 [32, 59, 123, 124, 60],
 [32, 59, 123, 124, 60, 61],
 [32, 59, 123, 124, 60, 61, 10]]

In [29]:
max_sequence_length = max(len(x) for x in input_sequences)
max_sequence_length

13

In [30]:
input_sequences = pad_sequences(input_sequences, maxlen = max_sequence_length, padding = "pre")
input_sequences

array([[  0,   0,   0, ...,   0, 118, 119],
       [  0,   0,   0, ..., 118, 119, 120],
       [  0,   0,   0, ..., 119, 120, 121],
       ...,
       [  0,   0,   0, ...,  16, 325,  25],
       [  0,   0,   0, ..., 325,  25,  38],
       [  0,   0,   0, ...,  25,  38,   9]])

In [55]:
x, y = input_sequences[:,:-1], input_sequences[:, -1]
# x mesela 1. satirda 1. sütundan sondan birinciye kadar olsun,
# y ise 1. satirin son sütunu olsun
# "x" ten "y" yi tahmin edicez yani
print("x :")
print(x[:5])
print("y (tahmni ediceimiz) :")
print(y[:5])

x :
[[  0   0   0   0   0   0   0   0   0   0   0 118]
 [  0   0   0   0   0   0   0   0   0   0 118 119]
 [  0   0   0   0   0   0   0   0   0 118 119 120]
 [  0   0   0   0   0   0   0   0 118 119 120 121]
 [  0   0   0   0   0   0   0   0   0   0   0  32]]
y (tahmni ediceimiz) :
[119 120 121 122  59]


In [56]:
y = tf.keras.utils.to_categorical(y, num_classes = total_words)

In [58]:
print(y[0])

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


create LSTM model

In [59]:
model = Sequential()
model.add(Embedding(total_words, 50, input_length = x.shape[1]))
model.add(LSTM(100, return_sequences = False))
model.add(Dense(total_words, activation = "softmax"))

In [60]:
model.compile(optimizer = "adam", loss = "categorical_crossentropy", metrics=["accuracy"])

train LSTM model

In [62]:
model.fit(x, y, epochs = 60, verbose = 1)

Epoch 1/60
20/20 [==============================] - 0s 13ms/step - loss: 1.3513 - accuracy: 0.7801
Epoch 2/60
20/20 [==============================] - 0s 12ms/step - loss: 1.3058 - accuracy: 0.7945
Epoch 3/60
20/20 [==============================] - 0s 12ms/step - loss: 1.2532 - accuracy: 0.7978
Epoch 4/60
20/20 [==============================] - 0s 11ms/step - loss: 1.2170 - accuracy: 0.8042
Epoch 5/60
20/20 [==============================] - 0s 11ms/step - loss: 1.1802 - accuracy: 0.8074
Epoch 6/60
20/20 [==============================] - 0s 12ms/step - loss: 1.1353 - accuracy: 0.8202
Epoch 7/60
20/20 [==============================] - 0s 12ms/step - loss: 1.0992 - accuracy: 0.8202
Epoch 8/60
20/20 [==============================] - 0s 13ms/step - loss: 1.0616 - accuracy: 0.8250
Epoch 9/60
20/20 [==============================] - 0s 12ms/step - loss: 1.0217 - accuracy: 0.8283
Epoch 10/60
20/20 [==============================] - 0s 11ms/step - loss: 0.9903 - accuracy: 0.8315
Epoch 11/

In [ ]:
def predict_next_word(seed_text, next_word):
    for _ in range(next_word):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen = max_sequence_length-1, padding = "pre")
        predicted_probs = model.predict(token_list, verbose = 0) # tüm y lerden hepsiinn olma olasiliğini çıakrdı
        predicted_word_inndex = np.argmax(predicted_probs, axis = -1) # tüm olasiliktan en yükselk olanı seçti
        predicted_word = tokenizer.index_word[predicted_word_inndex[0]] # en yüskke olasilikli oalnı yazdırdı
        seed_text = seed_text + " " + predicted_word # buraya da ekledi
    
    return seed_text

In [69]:
seed_text = "Yarın burada"
print(predict_next_word(seed_text, 1))
print(predict_next_word(seed_text, 3))
print(predict_next_word(seed_text, 10))

Yarın burada arkadaşlarımla
Yarın burada arkadaşlarımla buluşmaya gideceğim
Yarın burada arkadaşlarımla buluşmaya gideceğim gideceğim yavaşlamak gerek çok önemli var var
